<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AddNewClient.aspx.cs" Inherits="DB_Lab02.AddNewClient" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        
        <h3> Введите имя нового клиента</h3>
        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
        <asp:Button ID="Button1" runat="server" Text="Добавить" OnClick="Button1_Click" />
        <asp:Button ID="Button2" runat="server" Text="вывод таблицы DataSet" OnClick="Button2_Click" />
        <asp:Button ID="Button3" runat="server" Text="Удалить" OnClick="Button3_Click" /> <br /><br />


        <div>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:TruckingConnectionString %>" SelectCommand="SELECT * FROM [Client]" DeleteCommand="DELETE FROM [Client] WHERE [id] = @id" InsertCommand="INSERT INTO [Client] ([clientName]) VALUES (@clientName)" UpdateCommand="UPDATE [Client] SET [clientName] = @clientName WHERE [id] = @id">
                <DeleteParameters>
                    <asp:Parameter Name="id" Type="Int32"></asp:Parameter>
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="clientName" Type="String"></asp:Parameter>
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="clientName" Type="String"></asp:Parameter>
                    <asp:Parameter Name="id" Type="Int32"></asp:Parameter>
                </UpdateParameters>
            </asp:SqlDataSource>
             <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1">
                 <Columns>
                     <asp:BoundField DataField="id" HeaderText="№" InsertVisible="False" ReadOnly="True" SortExpression="id" />
                     <asp:BoundField DataField="clientName" HeaderText="Фамилия и имя " SortExpression="clientName" />
                 </Columns>
        </asp:GridView>
        </div>

        <div>
         <asp:Label ID="Label1" runat="server" Text=""></asp:Label>
        </div>        
    </form>
</body>
</html>
